---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[site-cineostypo3org::default]
    attributes:
      site-cineostypo3org:
        ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.42.42"}]
