name             'site-cineostypo3org'
maintainer       'Jacob Floyd'
maintainer_email 'cognifloyd@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures the CI server for Neos/Flow'
long_description 'Installs/Configures Jenkins for use in the Neos/Flow team on ci-neos.typo3.org'
version          '0.1.0'
depends          'jenkins', '~> 2.1.2'
depends          'nginx', '~> 1.6.0'
depends          'ssl_certificates'
